version: '3.3'

services:
  tv-server:
    build: .
    ports:
      - "8080:8080"
    
    # healthcheck:
    #   test: ["CMD", "curl", "-f", "http://localhost:8080/health"]  # Путь для проверки здоровья
    #   interval: 10s      # Интервал между проверками
    #   retries: 3         # Количество попыток перед тем как считать контейнер неработающим
    #   start_period: 5s  # Время, через которое начать проверки
    #   timeout: 5s
    # restart: no 