version: '3.3'

services:
  tv-server:
    build: .
    ports:
      - "8081:8080"
    restart: on-failure

  mysql:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tv
    ports:
      - "3306:3306"
    restart: on-failure
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    ports:
      - "8082:80"
    restart: on-failure